### ISSUE TITLE
Fresh installation on Ubuntu 16.04 fails with error

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/ubuntu#8]
Doing ``apt-get install privacyidea-apache2`` on a fresh Ubuntu 16.04, I get the following error message:

```
Traceback (most recent call last):
  File "/opt/privacyidea/bin/pi-manage", line 98, in <module>
    app = create_app(config_name='production', silent=SILENT)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/app.py", line 202, in create_app
    logging.config.dictConfig(PI_LOGGING_CONFIG)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/var/log/privacyidea/privacyidea.log'
```

This is because ``/var/log/privacyidea/`` does not exist. It can be fixed with
```shell
mkdir /var/log/privacyidea
chown privacyidea /var/log/privacyidea
apt-get -f install
```

**Comment by cornelinux** [comment]
Ach,
it happens here:
https://github.com/NetKnights-GmbH/ubuntu/blob/master/debian_server/privacyidea-apache2.postinst#L29

But it looks like stamping the DB is done to early - or create_files too late:
https://github.com/NetKnights-GmbH/ubuntu/blob/master/debian_server/privacyidea-apache2.postinst#L149

Will do!
