### ISSUE TITLE
privacyidea package contains unneeded files

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/ubuntu#9]
The privacyidea package contains another /etc/privacyidea directory inside the virtualenv:
```
$ dpkg -L privacyidea| grep  /etc
/opt/privacyidea/etc
/opt/privacyidea/etc/privacyidea
/opt/privacyidea/etc/privacyidea/dictionary
/opt/privacyidea/etc/privacyidea/privacyideaapp.wsgi
/opt/privacyidea/etc/privacyidea/enckey
/opt/privacyidea/etc/privacyidea/private.pem
/opt/privacyidea/etc/privacyidea/public.pem
```

The files aren't needed (and in fact, I'm not sure where they come from). They don't do any harm either, so I guess this isn't a high-priority issue.

**Comment by cornelinux** [comment]
These files come from the normal virtualenv pip installation.
When installing via pip, **in** the virtualenv an ``etc/`` directory is created.

**Comment by cornelinux** [comment]
Actually these files come from here:
https://github.com/privacyidea/privacyidea/blob/master/setup.py#L133

Hm, so we can close this issue in the privacyidea project
